### ISSUE TITLE
Invite teacher and course assistant to github/kanban board

### ISSUE THREAD

**Issue by rehnarama** [Melkster/voc#1]
According to instructions:

"In the group, use the Trello or GitHub system to track tasks. Use a suitable github client and IDE. Add the teacher and course assistant to your board and git repository by Friday 2019-09-06"

**Comment by jowe3751** [comment]
We have an answer from Raph!

**_Hi group F,

two teams (two and three people) are fine. Choose one math function (e.g. sin()) per pair/triplet. 

The "three additions" refer to the three bullet points following the general info on studentportalen, i.e. task tracking, writing a working note and understanding the control flow - in addition to following the VOC contribution guide.

My github handle is RaphaelaHeil

Hope this clarifies things. If not, please let me know!
/Raphaela_**
