### ISSUE TITLE
Pair1: Test and implement datetime work unit

### ISSUE THREAD

**Issue by rehnarama** [Melkster/voc#14]
For the work unit picked in #13,  "Add TranspilingTestsCases for your work unit and gradually add implementaions. Try to cover all conceivable inputs, edge cases and exceptions (if in doubt, refer to the Python documentation and follow their API specification). Finally, make yourself familiar with the [VOC guidelines](https://pybee.org/contributing/how/process/) regarding [code documentation](https://voc.readthedocs.io/en/latest/reference/signatures.html) and [code style](https://voc.readthedocs.io/en/latest/how-to/contribute.html#running-the-code-style-checks) and follow them closely in your implementations. "

Submit PR as with code review instructions! (i.e., how to run tests, what to look for, and so on).

Some documentation in code was more or less copied from Python (since it should mirror it anyways)

**Comment by rehnarama** [comment]
Closed by #37

**Comment by JonasNorlinder** [comment]
After talking to Davide it was okay to omit `resolution`.
