### ISSUE TITLE
Pair2: Evaluate performance of the new implementation against your conjecture

### ISSUE THREAD

**Issue by rehnarama** [Melkster/voc#28]
For the conjecture in #24 implemented in #26 , evaluate the performance against your conjecture.

Deliverable: What was the achieved performance? Expected or not? What's happening?

**Comment by AdamInersjo** [comment]
# Performance

## SumNumbers
* **Runtime**: 2.081259 s
* **Memory usage**: 1.7 GB

## InsertMany
* **Runtime**: 0.6056 s
* **Memory usage**: 57.6 MB

## RandomRemoves
* **Runtime**: 82.33 s
* **Memory usage**: 219.6 MB

**Comment by rehnarama** [comment]
Chart with measurements for sprint 3: [Measurements for sprint 3](http://user.it.uu.se/~mire2439/measurements-sprint3.pdf)

The chart shows that the runtime speed between the different implementations behaves exactly as we conjectured in #24.
