### ISSUE TITLE
Collect and consolidate the hand-in for sprint 3

### ISSUE THREAD

**Issue by rehnarama** [Melkster/voc#29]
To hand in by Thursday 2019-10-17 in Studentportalen (or by email to both Raphaela and Davide if SP is down): A brief report for each pair, describing your chosen workloads, performance measurements, alternative representation, conjecture, achieved performance, and conclusions.

**Comment by rehnarama** [comment]
Pair 2 has handed in their report

**Comment by jowe3751** [comment]
Pair 1 aswell
