### ISSUE TITLE
 Write JUnit test for List (Pair 1)

### ISSUE THREAD

**Issue by JonasNorlinder** [Melkster/voc#38]
According to #17, the following functions should be tested:

Jonas:
- [x] `public java.lang.Object toJava()`
- [x] `public int hashCode()`
- [x] `public org.python.Object __hash__()`
- [x] `public boolean isHashable()`
- [x] `public List()`
- [x] `public List(java.util.List<org.python.Object> list)`
- [x] `public List(org.python.Object[] args, java.util.Map<java.lang.String, org.python.Object> kwargs)`
- [ ] `public org.python.Object __new__()`
- [ ] `public org.python.Object __init__()`
- [x] `public org.python.Object __iadd__(org.python.Object other)`

Melker:
- [x] `public org.python.Object __bool__()`
- [ ] `public org.python.types.Str __repr__()`
- [ ] `public org.python.types.Str __format__()`
- [ ] `public org.python.Object __lt__(org.python.Object other)`
- [ ] `public org.python.Object __le__(org.python.Object other)`
- [ ] `public org.python.Object __eq__(org.python.Object other)`
- [ ] `public org.python.Object __gt__(org.python.Object other)`
- [ ] `public org.python.Object __ge__(org.python.Object other)`
- [ ] `public boolean __setattr_null(java.lang.String name, org.python.Object value)`
- [ ] `public org.python.types.Int __len__()`
- [ ] `public org.python.Object __getitem__(org.python.Object index)`

**Comment by JonasNorlinder** [comment]
Note: `public org.python.Object __iadd__(org.python.Object other)` it was not possible to coverage all lines

**Comment by mawkler** [comment]
Apparently we don't need to cover internal underscore functions, so I'll just finish up the `List` constructor and we should be done.
